---
title: "Overview"
author: "Christian McDonald"
---

[OpenRefine](https://openrefine.org/) is a powerful open source tool for working with messy data. Our most common use for it is to clean and transform data.

## Installation

The OpenRefine website has the [latest stable release](https://openrefine.org/download.html). They also have [extensive installation instructions](https://openrefine.org/docs/manual/installing#installing-or-upgrading), including some important tips Mac users on how to [circumvent security warnings](https://openrefine.org/docs/manual/installing#install-or-upgrade-openrefine) when launching the file.

While there is an OpenRefine application you launch, the program itself launches and uses your web browser for the interface.

## Walkthroughs

These are detailed demos with illustrated step-by-step instructions of commonly-used features of OpenRefine. If you are here to learn how to use OpenRefine, start with these.

- [Transforms & Facets](demo-facets.qmd)
- [Clustering](demo-cluster.qmd)

When going through these demos, know that numbered lists are steps for you to do:

1. Do this thing
1. And then this thing

Regular bullet lists are just information:

- This is just information
- It might be important. Or not.

## Case studies

These are some example use cases using OpenRefine. They are not tutorials, but discussions of how OpenRefine was used in some specific instances with key points explained.

- [AHRQ diagnostic codes](case-ahrq.qmd) pulled from a PDF.
- [Austin State Hospital cemetery](case-ash.qmd) burials where records are on more than one line.

## Resources

- [OpenRefine.org](https://openrefine.org/) has great documentation, tutorials, FAQs and more, including:
  - OpenRefine's [user manual](https://openrefine.org/docs):
  - [Expressions](https://openrefine.org/docs/manual/expressions)
  - [GREL functions](https://openrefine.org/docs/manual/grelfunctions)
